apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask
  labels:
    app: flask
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask
  template:
    metadata:
      labels:
        app: flask
    spec:
      initContainers:
        - name: wait-for-mysql
          image: busybox:1.36
          command:
            - sh
            - -c
            - |
              until nc -z mysql 3306; do
                echo "waiting for mysql...";
                sleep 3;
              done
      containers:
        - name: flask
          image: yg7821/devopsexamapp:v2
          imagePullPolicy: IfNotPresent
          ports:
            - name: port
              containerPort: 5000
          envFrom:
            - configMapRef:
                name: app-config
          env:
           - name: FLASK_SECRET_KEY
             valueFrom:
               secretKeyRef:
                 name: flask-secret
                 key: FLASK_SECRET_KEY
             name: MYSQL_PASSWORD
             valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_PASSWORD
          readinessProbe:
            tcpSocket:
              port: port
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: port
            initialDelaySeconds: 15
            periodSeconds: 20
