apiVersion: apps/v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: "rootpass"
  MYSQL_PASSWORD: "rootpass"
---
apiVersion: v1
kind: Secret
metadata:
  name: flask-secret
type: Opaque
stringData:
  FLASK_SECRET_KEY = "9688a5373da24ce27a7dfd8af69c3168935717fb966b6a80551b6f8499a331be"
